In [214]:
import pandas as pd

In [215]:
df = pd.read_csv("file/brands.csv")
print(df.head())
print(df.count())

  brand_code    brand_name category_code
0       ACME      AcmeTech            CE
1       ACME      AcmeTech            CE
2       NOVW    /NovaWave             CE
3       ZNTH        Zenith            CE
4       BYTM       ByteMax            CE
brand_code       57
brand_name       56
category_code    57
dtype: int64

In [216]:
df = df.drop_duplicates()
print(df.count())

brand_code       52
brand_name       51
category_code    52
dtype: int64

In [217]:
#d = df.drop(columns="category_code")
#print(d.head())

In [218]:
df.head()

  brand_code    brand_name category_code
0       ACME      AcmeTech            CE
2       NOVW    /NovaWave             CE
3       ZNTH        Zenith            CE
4       BYTM       ByteMax            CE
5       ECOT       EcoTone            CE

In [219]:
df["brand_name"] = df["brand_name"].str.replace(" ", "_")
print(df.head())

  brand_code    brand_name category_code
0       ACME      AcmeTech            CE
2       NOVW  __/NovaWave_            CE
3       ZNTH        Zenith            CE
4       BYTM       ByteMax            CE
5       ECOT       EcoTone            CE

In [220]:
#df["brand_name"] = df["brand_name"].str.lstrip("__/")
#print(df.head())

In [221]:
df["brand_name"]

0            AcmeTech
2        __/NovaWave_
3              Zenith
4             ByteMax
5             EcoTone
6          ...SkyLink
7            VoltEdge
9           /Photonix
10         UrbanTrail
11         CottonClub
15           _FitFlex
16         _AmberLeaf
17             __NaN_
18    __/NorthThread_
19         CobaltWear
20           CookMate
21           HomeNest
22         PureLiving
23           CasaNova
24           AquaPure
25         SteelCraft
26      __WarmHearth_
27          __GlowOn_
28       __HerbaCare_
29           DermaLux
30                NaN
31           AloeMist
32                N/a
33            BlueInk
34         PageTurner
35           ReadMore
36      __QuillHouse_
37           StoryArc
38         Leaf&Spine
39        FreshFields
40    __DailyHarvest_
41     __GreenBasket_
42     __NutriChoice_
43          GoodGrain
44            FarmJoy
45           PlayCube
46        __HappyFun_
47          GameForge
48          KiddoLand
49          TinyGears
50      __RocketBear_
51       __ProStride_
52        TrailBlazer
53            AeroFit
54            PeakPro
55      __SummitLine_
56       __SwiftCore_
Name: brand_name, dtype: str

In [222]:
#df["brand_name"] = df["brand_name"].str.lstrip("...")
#df["brand_name"] = df["brand_name"].str.rstrip("_")
df["brand_name"] = df["brand_name"].str.strip("123.12_/")

In [223]:
df

   brand_code    brand_name category_code
0        ACME      AcmeTech            CE
2        NOVW      NovaWave            CE
3        ZNTH        Zenith            CE
4        BYTM       ByteMax            CE
5        ECOT       EcoTone            CE
6        SKYL       SkyLink            CE
7       VOLT@      VoltEdge            CE
9        PHTX      Photonix            CE
10       URTL    UrbanTrail           APP
11       COTC    CottonClub           APP
15       FTFX       FitFlex           APP
16       ABLF     AmberLeaf           APP
17       MOSA           NaN           APP
18       NTHR   NorthThread           APP
19       CBLT    CobaltWear           APP
20      CKMT@      CookMate           HNK
21       HMNS      HomeNest           HNK
22       PRLV    PureLiving           HNK
23      CSNV@      CasaNova           HNK
24       AQPR      AquaPure           HNK
25       STCR    SteelCraft           HNK
26       WRMH    WarmHearth           HNK
27      GLOW*        GlowOn           BPC
28       HRBC     HerbaCare           BPC
29       DMLX      DermaLux           BPC
30       SLKE           NaN           BPC
31       ALMS      AloeMist           BPC
32       BTNQ           N/a           BPC
33       BLIN       BlueInk         BOOKS
34      PGTR@    PageTurner         BOOKS
35       RDMR      ReadMore         BOOKS
36      QLHS!    QuillHouse           BKS
37       STAC      StoryArc           BKS
38       LFSP    Leaf&Spine           BKS
39       FRFL   FreshFields       GROCERY
40       DLHV  DailyHarvest          GRCY
41       GRBK   GreenBasket       GROCERY
42       NTCH   NutriChoice          GRCY
43       GGRN     GoodGrain       GROCERY
44       FRMJ       FarmJoy          GRCY
45       PLCB      PlayCube           TOY
46      HPFN*      HappyFun          TOYS
47      GMFG@     GameForge           TOY
48       KDLN     KiddoLand          TOYS
49      TNGR@     TinyGears           TOY
50      RKBR*    RocketBear          TOYS
51       PRSD     ProStride           SPT
52       TRBZ   TrailBlazer           SPT
53       ARFT       AeroFit           SPT
54       PKPR       PeakPro           SPT
55       SMLN    SummitLine           SPT
56       SWCR     SwiftCore           SPT

In [224]:
#df["brand_name"].str.replace('[^a-cA-C0-1]', "_")

In [225]:
print(df.head())

  brand_code brand_name category_code
0       ACME   AcmeTech            CE
2       NOVW   NovaWave            CE
3       ZNTH     Zenith            CE
4       BYTM    ByteMax            CE
5       ECOT    EcoTone            CE

In [226]:
df["brand_name"] = df["brand_name"].apply(lambda x: str(x).capitalize())
print(df.head())

  brand_code brand_name category_code
0       ACME   Acmetech            CE
2       NOVW   Novawave            CE
3       ZNTH     Zenith            CE
4       BYTM    Bytemax            CE
5       ECOT    Ecotone            CE

In [227]:
df["brand_name"] = df["brand_name"].apply(lambda x: x[0:3]+"-"+x[3:])

In [228]:
df["brand_name"] = df["brand_name"].str.strip().str.lower().replace(["n/a-", "nan", "nn", "n/a"], "").str.capitalize()
print(df["brand_name"] )

0         Acm-etech
2         Nov-awave
3           Zen-ith
4          Byt-emax
5          Eco-tone
6          Sky-link
7         Vol-tedge
9         Pho-tonix
10      Urb-antrail
11      Cot-tonclub
15         Fit-flex
16       Amb-erleaf
17             Nan-
18     Nor-ththread
19      Cob-altwear
20        Coo-kmate
21        Hom-enest
22      Pur-eliving
23        Cas-anova
24        Aqu-apure
25      Ste-elcraft
26      War-mhearth
27          Glo-won
28       Her-bacare
29        Der-malux
30             Nan-
31        Alo-emist
32
33         Blu-eink
34      Pag-eturner
35        Rea-dmore
36      Qui-llhouse
37        Sto-ryarc
38      Lea-f&spine
39     Fre-shfields
40    Dai-lyharvest
41     Gre-enbasket
42     Nut-richoice
43       Goo-dgrain
44         Far-mjoy
45        Pla-ycube
46        Hap-pyfun
47       Gam-eforge
48       Kid-doland
49       Tin-ygears
50      Roc-ketbear
51       Pro-stride
52     Tra-ilblazer
53         Aer-ofit
54         Pea-kpro
55      Sum-mitline
56       Swi-ftcore
Name: brand_name, dtype: str

In [229]:
df[["brand", "name"]] = df["brand_name"].str.split('-', n=1, expand=True)
df["brand_name"] = df["brand_name"].str.replace("-","")

print(df.head())

  brand_code brand_name category_code brand   name
0       ACME   Acmetech            CE   Acm  etech
2       NOVW   Novawave            CE   Nov  awave
3       ZNTH     Zenith            CE   Zen    ith
4       BYTM    Bytemax            CE   Byt   emax
5       ECOT    Ecotone            CE   Eco   tone

In [230]:
df["brand_name"] = df["brand_name"].str.replace("Nan","Dermalux")
df["brand_name"]

0         Acmetech
2         Novawave
3           Zenith
4          Bytemax
5          Ecotone
6          Skylink
7         Voltedge
9         Photonix
10      Urbantrail
11      Cottonclub
15         Fitflex
16       Amberleaf
17        Dermalux
18     Norththread
19      Cobaltwear
20        Cookmate
21        Homenest
22      Pureliving
23        Casanova
24        Aquapure
25      Steelcraft
26      Warmhearth
27          Glowon
28       Herbacare
29        Dermalux
30        Dermalux
31        Aloemist
32
33         Blueink
34      Pageturner
35        Readmore
36      Quillhouse
37        Storyarc
38      Leaf&spine
39     Freshfields
40    Dailyharvest
41     Greenbasket
42     Nutrichoice
43       Goodgrain
44         Farmjoy
45        Playcube
46        Happyfun
47       Gameforge
48       Kiddoland
49       Tinygears
50      Rocketbear
51       Prostride
52     Trailblazer
53         Aerofit
54         Peakpro
55      Summitline
56       Swiftcore
Name: brand_name, dtype: str

In [231]:
print(df)

   brand_code    brand_name category_code brand       name
0        ACME      Acmetech            CE   Acm      etech
2        NOVW      Novawave            CE   Nov      awave
3        ZNTH        Zenith            CE   Zen        ith
4        BYTM       Bytemax            CE   Byt       emax
5        ECOT       Ecotone            CE   Eco       tone
6        SKYL       Skylink            CE   Sky       link
7       VOLT@      Voltedge            CE   Vol      tedge
9        PHTX      Photonix            CE   Pho      tonix
10       URTL    Urbantrail           APP   Urb    antrail
11       COTC    Cottonclub           APP   Cot    tonclub
15       FTFX       Fitflex           APP   Fit       flex
16       ABLF     Amberleaf           APP   Amb     erleaf
17       MOSA      Dermalux           APP   Nan
18       NTHR   Norththread           APP   Nor   ththread
19       CBLT    Cobaltwear           APP   Cob    altwear
20      CKMT@      Cookmate           HNK   Coo      kmate
21       HMNS      Homenest           HNK   Hom      enest
22       PRLV    Pureliving           HNK   Pur    eliving
23      CSNV@      Casanova           HNK   Cas      anova
24       AQPR      Aquapure           HNK   Aqu      apure
25       STCR    Steelcraft           HNK   Ste    elcraft
26       WRMH    Warmhearth           HNK   War    mhearth
27      GLOW*        Glowon           BPC   Glo        won
28       HRBC     Herbacare           BPC   Her     bacare
29       DMLX      Dermalux           BPC   Der      malux
30       SLKE      Dermalux           BPC   Nan
31       ALMS      Aloemist           BPC   Alo      emist
32       BTNQ                         BPC              NaN
33       BLIN       Blueink         BOOKS   Blu       eink
34      PGTR@    Pageturner         BOOKS   Pag    eturner
35       RDMR      Readmore         BOOKS   Rea      dmore
36      QLHS!    Quillhouse           BKS   Qui    llhouse
37       STAC      Storyarc           BKS   Sto      ryarc
38       LFSP    Leaf&spine           BKS   Lea    f&spine
39       FRFL   Freshfields       GROCERY   Fre   shfields
40       DLHV  Dailyharvest          GRCY   Dai  lyharvest
41       GRBK   Greenbasket       GROCERY   Gre   enbasket
42       NTCH   Nutrichoice          GRCY   Nut   richoice
43       GGRN     Goodgrain       GROCERY   Goo     dgrain
44       FRMJ       Farmjoy          GRCY   Far       mjoy
45       PLCB      Playcube           TOY   Pla      ycube
46      HPFN*      Happyfun          TOYS   Hap      pyfun
47      GMFG@     Gameforge           TOY   Gam     eforge
48       KDLN     Kiddoland          TOYS   Kid     doland
49      TNGR@     Tinygears           TOY   Tin     ygears
50      RKBR*    Rocketbear          TOYS   Roc    ketbear
51       PRSD     Prostride           SPT   Pro     stride
52       TRBZ   Trailblazer           SPT   Tra   ilblazer
53       ARFT       Aerofit           SPT   Aer       ofit
54       PKPR       Peakpro           SPT   Pea       kpro
55       SMLN    Summitline           SPT   Sum    mitline
56       SWCR     Swiftcore           SPT   Swi     ftcore

In [232]:
empty = df.isnull()
print(empty)

    brand_code  brand_name  category_code  brand   name
0        False       False          False  False  False
2        False       False          False  False  False
3        False       False          False  False  False
4        False       False          False  False  False
5        False       False          False  False  False
6        False       False          False  False  False
7        False       False          False  False  False
9        False       False          False  False  False
10       False       False          False  False  False
11       False       False          False  False  False
15       False       False          False  False  False
16       False       False          False  False  False
17       False       False          False  False  False
18       False       False          False  False  False
19       False       False          False  False  False
20       False       False          False  False  False
21       False       False          False  False  False
22       False       False          False  False  False
23       False       False          False  False  False
24       False       False          False  False  False
25       False       False          False  False  False
26       False       False          False  False  False
27       False       False          False  False  False
28       False       False          False  False  False
29       False       False          False  False  False
30       False       False          False  False  False
31       False       False          False  False  False
32       False       False          False  False   True
33       False       False          False  False  False
34       False       False          False  False  False
35       False       False          False  False  False
36       False       False          False  False  False
37       False       False          False  False  False
38       False       False          False  False  False
39       False       False          False  False  False
40       False       False          False  False  False
41       False       False          False  False  False
42       False       False          False  False  False
43       False       False          False  False  False
44       False       False          False  False  False
45       False       False          False  False  False
46       False       False          False  False  False
47       False       False          False  False  False
48       False       False          False  False  False
49       False       False          False  False  False
50       False       False          False  False  False
51       False       False          False  False  False
52       False       False          False  False  False
53       False       False          False  False  False
54       False       False          False  False  False
55       False       False          False  False  False
56       False       False          False  False  False

In [233]:
df = df[df["brand_name"].str.contains(r'[a-zA-Z0-1]', na=False)]
print(df)

   brand_code    brand_name category_code brand       name
0        ACME      Acmetech            CE   Acm      etech
2        NOVW      Novawave            CE   Nov      awave
3        ZNTH        Zenith            CE   Zen        ith
4        BYTM       Bytemax            CE   Byt       emax
5        ECOT       Ecotone            CE   Eco       tone
6        SKYL       Skylink            CE   Sky       link
7       VOLT@      Voltedge            CE   Vol      tedge
9        PHTX      Photonix            CE   Pho      tonix
10       URTL    Urbantrail           APP   Urb    antrail
11       COTC    Cottonclub           APP   Cot    tonclub
15       FTFX       Fitflex           APP   Fit       flex
16       ABLF     Amberleaf           APP   Amb     erleaf
17       MOSA      Dermalux           APP   Nan
18       NTHR   Norththread           APP   Nor   ththread
19       CBLT    Cobaltwear           APP   Cob    altwear
20      CKMT@      Cookmate           HNK   Coo      kmate
21       HMNS      Homenest           HNK   Hom      enest
22       PRLV    Pureliving           HNK   Pur    eliving
23      CSNV@      Casanova           HNK   Cas      anova
24       AQPR      Aquapure           HNK   Aqu      apure
25       STCR    Steelcraft           HNK   Ste    elcraft
26       WRMH    Warmhearth           HNK   War    mhearth
27      GLOW*        Glowon           BPC   Glo        won
28       HRBC     Herbacare           BPC   Her     bacare
29       DMLX      Dermalux           BPC   Der      malux
30       SLKE      Dermalux           BPC   Nan
31       ALMS      Aloemist           BPC   Alo      emist
33       BLIN       Blueink         BOOKS   Blu       eink
34      PGTR@    Pageturner         BOOKS   Pag    eturner
35       RDMR      Readmore         BOOKS   Rea      dmore
36      QLHS!    Quillhouse           BKS   Qui    llhouse
37       STAC      Storyarc           BKS   Sto      ryarc
38       LFSP    Leaf&spine           BKS   Lea    f&spine
39       FRFL   Freshfields       GROCERY   Fre   shfields
40       DLHV  Dailyharvest          GRCY   Dai  lyharvest
41       GRBK   Greenbasket       GROCERY   Gre   enbasket
42       NTCH   Nutrichoice          GRCY   Nut   richoice
43       GGRN     Goodgrain       GROCERY   Goo     dgrain
44       FRMJ       Farmjoy          GRCY   Far       mjoy
45       PLCB      Playcube           TOY   Pla      ycube
46      HPFN*      Happyfun          TOYS   Hap      pyfun
47      GMFG@     Gameforge           TOY   Gam     eforge
48       KDLN     Kiddoland          TOYS   Kid     doland
49      TNGR@     Tinygears           TOY   Tin     ygears
50      RKBR*    Rocketbear          TOYS   Roc    ketbear
51       PRSD     Prostride           SPT   Pro     stride
52       TRBZ   Trailblazer           SPT   Tra   ilblazer
53       ARFT       Aerofit           SPT   Aer       ofit
54       PKPR       Peakpro           SPT   Pea       kpro
55       SMLN    Summitline           SPT   Sum    mitline
56       SWCR     Swiftcore           SPT   Swi     ftcore

In [235]:
for x in df.index:
    if df.loc[x, "name"] == " ":
        df.loc[x, "name"] = "XX"
print(df)

   brand_code    brand_name category_code brand       name
0        ACME      Acmetech            CE   Acm      etech
2        NOVW      Novawave            CE   Nov      awave
3        ZNTH        Zenith            CE   Zen        ith
4        BYTM       Bytemax            CE   Byt       emax
5        ECOT       Ecotone            CE   Eco       tone
6        SKYL       Skylink            CE   Sky       link
7       VOLT@      Voltedge            CE   Vol      tedge
9        PHTX      Photonix            CE   Pho      tonix
10       URTL    Urbantrail           APP   Urb    antrail
11       COTC    Cottonclub           APP   Cot    tonclub
15       FTFX       Fitflex           APP   Fit       flex
16       ABLF     Amberleaf           APP   Amb     erleaf
17       MOSA      Dermalux           APP   Nan
18       NTHR   Norththread           APP   Nor   ththread
19       CBLT    Cobaltwear           APP   Cob    altwear
20      CKMT@      Cookmate           HNK   Coo      kmate
21       HMNS      Homenest           HNK   Hom      enest
22       PRLV    Pureliving           HNK   Pur    eliving
23      CSNV@      Casanova           HNK   Cas      anova
24       AQPR      Aquapure           HNK   Aqu      apure
25       STCR    Steelcraft           HNK   Ste    elcraft
26       WRMH    Warmhearth           HNK   War    mhearth
27      GLOW*        Glowon           BPC   Glo        won
28       HRBC     Herbacare           BPC   Her     bacare
29       DMLX      Dermalux           BPC   Der      malux
30       SLKE      Dermalux           BPC   Nan
31       ALMS      Aloemist           BPC   Alo      emist
33       BLIN       Blueink         BOOKS   Blu       eink
34      PGTR@    Pageturner         BOOKS   Pag    eturner
35       RDMR      Readmore         BOOKS   Rea      dmore
36      QLHS!    Quillhouse           BKS   Qui    llhouse
37       STAC      Storyarc           BKS   Sto      ryarc
38       LFSP    Leaf&spine           BKS   Lea    f&spine
39       FRFL   Freshfields       GROCERY   Fre   shfields
40       DLHV  Dailyharvest          GRCY   Dai  lyharvest
41       GRBK   Greenbasket       GROCERY   Gre   enbasket
42       NTCH   Nutrichoice          GRCY   Nut   richoice
43       GGRN     Goodgrain       GROCERY   Goo     dgrain
44       FRMJ       Farmjoy          GRCY   Far       mjoy
45       PLCB      Playcube           TOY   Pla      ycube
46      HPFN*      Happyfun          TOYS   Hap      pyfun
47      GMFG@     Gameforge           TOY   Gam     eforge
48       KDLN     Kiddoland          TOYS   Kid     doland
49      TNGR@     Tinygears           TOY   Tin     ygears
50      RKBR*    Rocketbear          TOYS   Roc    ketbear
51       PRSD     Prostride           SPT   Pro     stride
52       TRBZ   Trailblazer           SPT   Tra   ilblazer
53       ARFT       Aerofit           SPT   Aer       ofit
54       PKPR       Peakpro           SPT   Pea       kpro
55       SMLN    Summitline           SPT   Sum    mitline
56       SWCR     Swiftcore           SPT   Swi     ftcore

In [236]:
df.isna().sum()

brand_code       0
brand_name       0
category_code    0
brand            0
name             0
dtype: int64

In [237]:
# Find rows where any column is empty or just whitespace
missing_rows = df[(df.astype(str).apply(lambda x: x.str.strip() == "")).any(axis=1)]
print(missing_rows)

   brand_code brand_name category_code brand name
17       MOSA   Dermalux           APP   Nan
30       SLKE   Dermalux           BPC   Nan

In [238]:
df.isna().sum()

brand_code       0
brand_name       0
category_code    0
brand            0
name             0
dtype: int64

In [241]:
import numpy as np
df = df.replace(r'^\s*$', np.nan, regex=True)
print(df)

   brand_code    brand_name category_code brand       name
0        ACME      Acmetech            CE   Acm      etech
2        NOVW      Novawave            CE   Nov      awave
3        ZNTH        Zenith            CE   Zen        ith
4        BYTM       Bytemax            CE   Byt       emax
5        ECOT       Ecotone            CE   Eco       tone
6        SKYL       Skylink            CE   Sky       link
7       VOLT@      Voltedge            CE   Vol      tedge
9        PHTX      Photonix            CE   Pho      tonix
10       URTL    Urbantrail           APP   Urb    antrail
11       COTC    Cottonclub           APP   Cot    tonclub
15       FTFX       Fitflex           APP   Fit       flex
16       ABLF     Amberleaf           APP   Amb     erleaf
17       MOSA      Dermalux           APP   Nan        NaN
18       NTHR   Norththread           APP   Nor   ththread
19       CBLT    Cobaltwear           APP   Cob    altwear
20      CKMT@      Cookmate           HNK   Coo      kmate
21       HMNS      Homenest           HNK   Hom      enest
22       PRLV    Pureliving           HNK   Pur    eliving
23      CSNV@      Casanova           HNK   Cas      anova
24       AQPR      Aquapure           HNK   Aqu      apure
25       STCR    Steelcraft           HNK   Ste    elcraft
26       WRMH    Warmhearth           HNK   War    mhearth
27      GLOW*        Glowon           BPC   Glo        won
28       HRBC     Herbacare           BPC   Her     bacare
29       DMLX      Dermalux           BPC   Der      malux
30       SLKE      Dermalux           BPC   Nan        NaN
31       ALMS      Aloemist           BPC   Alo      emist
33       BLIN       Blueink         BOOKS   Blu       eink
34      PGTR@    Pageturner         BOOKS   Pag    eturner
35       RDMR      Readmore         BOOKS   Rea      dmore
36      QLHS!    Quillhouse           BKS   Qui    llhouse
37       STAC      Storyarc           BKS   Sto      ryarc
38       LFSP    Leaf&spine           BKS   Lea    f&spine
39       FRFL   Freshfields       GROCERY   Fre   shfields
40       DLHV  Dailyharvest          GRCY   Dai  lyharvest
41       GRBK   Greenbasket       GROCERY   Gre   enbasket
42       NTCH   Nutrichoice          GRCY   Nut   richoice
43       GGRN     Goodgrain       GROCERY   Goo     dgrain
44       FRMJ       Farmjoy          GRCY   Far       mjoy
45       PLCB      Playcube           TOY   Pla      ycube
46      HPFN*      Happyfun          TOYS   Hap      pyfun
47      GMFG@     Gameforge           TOY   Gam     eforge
48       KDLN     Kiddoland          TOYS   Kid     doland
49      TNGR@     Tinygears           TOY   Tin     ygears
50      RKBR*    Rocketbear          TOYS   Roc    ketbear
51       PRSD     Prostride           SPT   Pro     stride
52       TRBZ   Trailblazer           SPT   Tra   ilblazer
53       ARFT       Aerofit           SPT   Aer       ofit
54       PKPR       Peakpro           SPT   Pea       kpro
55       SMLN    Summitline           SPT   Sum    mitline
56       SWCR     Swiftcore           SPT   Swi     ftcore

In [242]:
df.isna().sum()

brand_code       0
brand_name       0
category_code    0
brand            0
name             2
dtype: int64